// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProofOfConcept_TPH_vs_2_queries;

#nullable disable

namespace ProofOfConcept_TPH_vs_join.Migrations.TphDb
{
    [DbContext(typeof(TphDbContext))]
    [Migration("20250119142725_test_tph")]
    partial class test_tph
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tph")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProofOfConcept_TPH_vs_2_queries.Entities.Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Entities", "tph");

                    b.HasDiscriminator().HasValue("Entity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProofOfConcept_TPH_vs_2_queries.Entities.EntityTph1", b =>
                {
                    b.HasBaseType("ProofOfConcept_TPH_vs_2_queries.Entities.Entity");

                    b.Property<int>("F12")
                        .HasColumnType("integer");

                    b.Property<int>("F13")
                        .HasColumnType("integer");

                    b.Property<int>("F14")
                        .HasColumnType("integer");

                    b.Property<int>("F15")
                        .HasColumnType("integer");

                    b.Property<int>("F16")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("EntityTph1");
                });

            modelBuilder.Entity("ProofOfConcept_TPH_vs_2_queries.Entities.EntityTph2", b =>
                {
                    b.HasBaseType("ProofOfConcept_TPH_vs_2_queries.Entities.Entity");

                    b.Property<int>("F22")
                        .HasColumnType("integer");

                    b.Property<int>("F23")
                        .HasColumnType("integer");

                    b.Property<int>("F24")
                        .HasColumnType("integer");

                    b.Property<int>("F25")
                        .HasColumnType("integer");

                    b.Property<int>("F26")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("EntityTph2");
                });

            modelBuilder.Entity("ProofOfConcept_TPH_vs_2_queries.Entities.EntityTph3", b =>
                {
                    b.HasBaseType("ProofOfConcept_TPH_vs_2_queries.Entities.Entity");

                    b.Property<int>("F32")
                        .HasColumnType("integer");

                    b.Property<int>("F33")
                        .HasColumnType("integer");

                    b.Property<int>("F34")
                        .HasColumnType("integer");

                    b.Property<int>("F35")
                        .HasColumnType("integer");

                    b.Property<int>("F36")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("EntityTph3");
                });

            modelBuilder.Entity("ProofOfConcept_TPH_vs_2_queries.Entities.EntityTph4", b =>
                {
                    b.HasBaseType("ProofOfConcept_TPH_vs_2_queries.Entities.Entity");

                    b.Property<int>("F42")
                        .HasColumnType("integer");

                    b.Property<int>("F43")
                        .HasColumnType("integer");

                    b.Property<int>("F44")
                        .HasColumnType("integer");

                    b.Property<int>("F45")
                        .HasColumnType("integer");

                    b.Property<int>("F46")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("EntityTph4");
                });
#pragma warning restore 612, 618
        }
    }
}
